# Force canonical host - Hero image order fix v3 - Cache clear
[[redirects]]
  from = "https://www.caboweddingplanner.love/*"
  to   = "https://caboweddingplanner.love/:splat"
  status = 301
  force  = true

# Security + OPTIMIZED caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    # FIXED: Allow caching for HTML with short cache time
    Cache-Control = "public, max-age=300, s-maxage=300"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add caching for all image formats
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/og/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Preload critical resources - Updated for hero image order fix
[[headers]]
  for = "/"
  [headers.values]
    Link = '</hero-1.jpg>; rel=preload; as=image; fetchpriority=high, </fonts/inter-var.woff2>; rel=preload; as=font; type=font/woff2; crossorigin' 